package frostsigner

import (
	"context"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"strings"
	"sync"
	"time"

	secp "github.com/decred/dcrd/dcrec/secp256k1/v4"

	"github.com/GracedEternalKingCabbageMan/openamp/openampd/internal/store"
)

// The in-process transport: every quorum member is a distinct role with its own
// polynomial, its own share and its own nonces, but they run in one process and
// persist to one 0600 keys file. See doc.go for exactly what that posture does
// and does not prove.

// pendingKeyPrefix marks a provisional KeyID, used between GeneratePolicyKey
// and Adopt (openampd only learns an asset id after issuance derives it).
const pendingKeyPrefix = "pending:"

// storagePrefix maps a KeyID to the keys-file prefix the in-process member and
// coordinator store under. The staged and bound layouts are the ones openampd
// has always used, so key material generated by earlier versions is found
// unchanged:
//
//	frost-pending:<ref>:share:<i>   staged member share
//	frost:<assetID>:share:<i>       bound member share
//	frost:<assetID>:group           group public key
//	frost:<assetID>:pubshare:<i>    member i's public share (pinned at keygen)
//
// A networked member stores however it likes; the KeyID is all it is given.
func storagePrefix(keyID string) string {
	if ref, ok := strings.CutPrefix(keyID, pendingKeyPrefix); ok {
		return "frost-pending:" + ref + ":"
	}
	return "frost:" + keyID + ":"
}

// sessionTTL bounds how long a member keeps state for a round nobody finished.
// It is the backstop for the coordinator dying mid-round: without it, nonces
// whose commitments are already public would wait indefinitely for a message.
const sessionTTL = 15 * time.Minute

// LocalTransport runs all n members in this process, over one key store.
type LocalTransport struct {
	members map[int]*localMember
	ids     []Identity
}

// NewLocalTransport builds the in-process quorum. Every member draws its
// secrets from rnd; pass a deterministic reader to reproduce a run.
//
// The reader is shared by all n members and openampd signs concurrently, so it
// is wrapped in a lock here: crypto/rand.Reader is safe on its own, but the
// deterministic readers this constructor invites are not, and a torn read of a
// nonce is not a failure mode worth risking.
func NewLocalTransport(st *store.Store, n int, rnd io.Reader) *LocalTransport {
	shared := &lockedReader{r: rnd}
	t := &LocalTransport{members: make(map[int]*localMember, n)}
	for id := 1; id <= n; id++ {
		t.members[id] = &localMember{
			id: id, st: st, rnd: shared,
			dkg:    map[string]*dkgState{},
			nonces: map[string]*nonceState{},
			peer:   t.Member,
		}
		t.ids = append(t.ids, Identity{ID: id, Name: fmt.Sprintf("member-%d", id)})
	}
	return t
}

// lockedReader serializes access to a shared entropy source.
type lockedReader struct {
	mu sync.Mutex
	r  io.Reader
}

func (l *lockedReader) Read(p []byte) (int, error) {
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.r.Read(p)
}

func (t *LocalTransport) Members() []Identity { return t.ids }

func (t *LocalTransport) Member(id int) (Member, error) {
	m, ok := t.members[id]
	if !ok {
		return nil, fmt.Errorf("no member %d in this quorum: %w", id, ErrUnreachable)
	}
	return m, nil
}

// Close is a no-op: an in-process member holds no connection. Its share stays
// in the keys file, which is the daemon's to manage.
func (t *LocalTransport) Close() error { return nil }

// InstallDealtShares hands each member a share generated OUTSIDE the quorum,
// which is only meaningful for the trusted-dealer keygen mode. It exists on the
// in-process transport alone: a member on its own host must refuse material it
// did not help generate, which is precisely the property the DKG provides. This
// is therefore also the method a networked transport must NOT implement.
func (t *LocalTransport) InstallDealtShares(keyID string, shares map[int][32]byte) error {
	for _, id := range sortedIDs(shares) {
		m, ok := t.members[id]
		if !ok {
			return fmt.Errorf("no member %d in this quorum", id)
		}
		sh := shares[id]
		if err := m.st.SaveKey(m.shareName(keyID), hex.EncodeToString(sh[:])); err != nil {
			return err
		}
	}
	return nil
}

// dkgState is one member's per-session DKG state. The polynomial is dropped at
// Finalize, so it never outlives the run that used it; the rest survives only
// until AbortDKG rolls the run back or the state expires.
type dkgState struct {
	session   DKGSession
	poly      *polynomial
	own       *DKGCommitment
	peerComms map[int]*DKGCommitment // set at Deal, needed to verify received shares
	received  map[int][32]byte       // shares addressed to this member, by sender
	dealt     bool
	persisted string    // KeyID written at Finalize; AbortDKG rolls it back
	created   time.Time // for expiry
}

// nonceState is one member's live signing nonces. Deleted the moment a partial
// signature is produced: reusing a nonce pair across two messages leaks the
// share, so single use is enforced by destruction, not by convention.
type nonceState struct {
	keyID   string
	hiding  *secp.ModNScalar
	bind    *secp.ModNScalar
	D, E    []byte
	created time.Time // for expiry
}

// localMember is one quorum member in this process.
type localMember struct {
	id   int
	st   *store.Store
	rnd  io.Reader
	peer func(id int) (Member, error)

	mu     sync.Mutex
	dkg    map[string]*dkgState
	nonces map[string]*nonceState
}

func (m *localMember) Identity() Identity {
	return Identity{ID: m.id, Name: fmt.Sprintf("member-%d", m.id)}
}

func (m *localMember) shareName(keyID string) string {
	return fmt.Sprintf("%sshare:%d", storagePrefix(keyID), m.id)
}

// --- DKG ---------------------------------------------------------------------

func (m *localMember) Commit(_ context.Context, s DKGSession) (*DKGCommitment, error) {
	if !inSession(s, m.id) {
		return nil, fmt.Errorf("member %d: not a member of session %s", m.id, s.ID)
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	m.expireLocked()
	if _, exists := m.dkg[s.ID]; exists {
		return nil, fmt.Errorf("member %d: DKG session %s already started", m.id, s.ID)
	}
	poly, err := newPolynomial(s.Threshold, m.rnd)
	if err != nil {
		return nil, err
	}
	comm, err := poly.commit(m.id, s.ID, m.rnd)
	if err != nil {
		return nil, err
	}
	m.dkg[s.ID] = &dkgState{
		session: s, poly: poly, own: comm,
		received: map[int][32]byte{}, created: time.Now(),
	}
	return comm, nil
}

func (m *localMember) Deal(ctx context.Context, s DKGSession, comms map[int]*DKGCommitment) error {
	m.mu.Lock()
	st, ok := m.dkg[s.ID]
	if !ok {
		m.mu.Unlock()
		return fmt.Errorf("member %d: unknown DKG session %s", m.id, s.ID)
	}
	// The session is the one this member committed to, not whatever the caller
	// passes now: otherwise a run could start under one member set or KeyID and
	// continue under another.
	if err := sameSession(st.session, s); err != nil {
		m.mu.Unlock()
		return fmt.Errorf("member %d: %w", m.id, err)
	}
	if st.dealt {
		m.mu.Unlock()
		return fmt.Errorf("member %d: already dealt in session %s", m.id, s.ID)
	}
	// The commitment set must be exactly this session's membership. The group
	// key is the SUM of these commitments, so one extra well-formed entry would
	// shift it while every other check still passed — and the members, all
	// deriving the same wrong key, would agree with each other.
	if err := checkCommitmentSet(st.session, comms); err != nil {
		m.mu.Unlock()
		return err
	}
	// Verify every peer's proof of knowledge BEFORE contributing a share: a
	// member must not deal into a session whose group key another member could
	// have steered.
	for _, id := range sortedIDs(comms) {
		if err := verifyCommitment(s.ID, st.session.Threshold, comms[id]); err != nil {
			m.mu.Unlock()
			return err
		}
	}
	if mine, has := comms[m.id]; !has || !sameCommitment(mine, st.own) {
		m.mu.Unlock()
		return fmt.Errorf("member %d: the broadcast commitment set does not carry my own commitment", m.id)
	}
	// Copy: the caller's map is shared with every other in-process member.
	pinned := make(map[int]*DKGCommitment, len(comms))
	for id, c := range comms {
		pinned[id] = c
	}
	st.peerComms = pinned
	st.dealt = true
	poly := st.poly
	members := st.session.Members
	m.mu.Unlock()

	// Push each member (including this one) the share it is owed. The
	// coordinator never sees these: Deal returns only an error.
	for _, ident := range members {
		peer, err := m.peer(ident.ID)
		if err != nil {
			return fmt.Errorf("member %d: reaching member %d: %w", m.id, ident.ID, err)
		}
		sh := &DKGShare{From: m.id, To: ident.ID, Value: poly.eval(ident.ID).Bytes()}
		if err := peer.AcceptShare(ctx, s.ID, sh); err != nil {
			return fmt.Errorf("member %d: delivering share to member %d: %w", m.id, ident.ID, err)
		}
	}
	return nil
}

func (m *localMember) AcceptShare(_ context.Context, sessionID string, sh *DKGShare) error {
	if sh == nil {
		return fmt.Errorf("member %d: nil share", m.id)
	}
	if sh.To != m.id {
		return fmt.Errorf("member %d: share addressed to member %d", m.id, sh.To)
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	st, ok := m.dkg[sessionID]
	if !ok {
		// The coordinator completes round 1 with every member before any Deal, so
		// an unknown session here is a protocol violation, not a race.
		return fmt.Errorf("member %d: share for unknown DKG session %s", m.id, sessionID)
	}
	if !inSession(st.session, sh.From) {
		return fmt.Errorf("member %d: share from %d, which is not in session %s", m.id, sh.From, sessionID)
	}
	if _, dup := st.received[sh.From]; dup {
		return misbehaved(sh.From, "sent member %d two shares in one session", m.id)
	}
	st.received[sh.From] = sh.Value
	return nil
}

func (m *localMember) Finalize(_ context.Context, s DKGSession) (*DKGResult, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	st, ok := m.dkg[s.ID]
	if !ok {
		return nil, fmt.Errorf("member %d: unknown DKG session %s", m.id, s.ID)
	}
	if err := sameSession(st.session, s); err != nil {
		return nil, fmt.Errorf("member %d: %w", m.id, err)
	}
	if st.persisted != "" {
		return nil, fmt.Errorf("member %d: session %s already finalized", m.id, s.ID)
	}
	if !st.dealt {
		return nil, fmt.Errorf("member %d: cannot finalize session %s before dealing", m.id, s.ID)
	}
	// Every member must have dealt to this one, and every share must match the
	// commitments its sender published. THIS is the Feldman verification, run by
	// the only party that holds the share: the recipient.
	share := new(secp.ModNScalar)
	for _, ident := range st.session.Members {
		value, has := st.received[ident.ID]
		if !has {
			return nil, fmt.Errorf("member %d: no share received from member %d: %w", m.id, ident.ID, ErrUnreachable)
		}
		comm, has := st.peerComms[ident.ID]
		if !has {
			return nil, fmt.Errorf("member %d: no commitments for member %d", m.id, ident.ID)
		}
		if err := verifyShare(comm, &DKGShare{From: ident.ID, To: m.id, Value: value}); err != nil {
			return nil, err
		}
		var v secp.ModNScalar
		v.SetBytes(&value)
		share.Add(&v)
	}
	if share.IsZero() {
		return nil, fmt.Errorf("member %d: aggregate share is zero", m.id)
	}
	P, err := groupPoint(st.peerComms)
	if err != nil {
		return nil, err
	}
	b := share.Bytes()
	if err := m.st.SaveKey(m.shareName(st.session.KeyID), hex.EncodeToString(b[:])); err != nil {
		return nil, err
	}
	st.persisted = st.session.KeyID
	// The polynomial and the received shares have done their job; only the
	// aggregate share (now in the keys file) survives. The husk stays until
	// AbortDKG can roll the write back or the state expires.
	st.poly, st.received, st.peerComms, st.own = nil, nil, nil, nil
	return &DKGResult{GroupKey: compressPoint(P)}, nil
}

// AbortDKG discards session state and deletes anything Finalize persisted for
// it. This rollback is what makes a failed DKG leave no partial key set behind.
func (m *localMember) AbortDKG(_ context.Context, sessionID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.abortDKGLocked(sessionID)
}

func (m *localMember) abortDKGLocked(sessionID string) error {
	st, ok := m.dkg[sessionID]
	if !ok {
		return nil // unknown session: nothing to roll back
	}
	delete(m.dkg, sessionID)
	if st.persisted == "" {
		return nil
	}
	if err := m.st.DeleteKey(m.shareName(st.persisted)); err != nil {
		return fmt.Errorf("member %d: rolling back share for key %s: %w", m.id, st.persisted, err)
	}
	log.Printf("frost: member %d rolled back its share for aborted session %s", m.id, sessionID)
	return nil
}

// AbortSign drops the nonces held for a signing session that will not complete.
func (m *localMember) AbortSign(_ context.Context, sessionID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.nonces, sessionID)
	return nil
}

// expireLocked drops stale rounds. Unused nonces are the reason it exists: a
// coordinator that dies between the two signing rounds would otherwise leave a
// live nonce pair, with its commitments already public, for any later caller to
// consume. Keygen sessions expire too, so a daemon that provisions keys for
// years does not accumulate husks.
func (m *localMember) expireLocked() {
	for id, ns := range m.nonces {
		if time.Since(ns.created) > sessionTTL {
			delete(m.nonces, id)
		}
	}
	for id, st := range m.dkg {
		if time.Since(st.created) <= sessionTTL {
			continue
		}
		if st.persisted != "" {
			// A finalized-but-never-adopted run: the share is real key material
			// the coordinator may still adopt, so expiring the husk must not
			// delete it. Drop only the in-memory state.
			delete(m.dkg, id)
			continue
		}
		_ = m.abortDKGLocked(id)
	}
}

// --- key binding -------------------------------------------------------------

func (m *localMember) Adopt(_ context.Context, fromKeyID, toKeyID string) error {
	keys, err := m.st.LoadKeys()
	if err != nil {
		return err
	}
	to := m.shareName(toKeyID)
	from := m.shareName(fromKeyID)
	if _, done := keys[to]; done {
		// Idempotent: already adopted. Drop any staged copy left by a retried
		// adopt so the member owns exactly one entry per key.
		return m.st.DeleteKey(from)
	}
	if _, has := keys[from]; !has {
		return fmt.Errorf("member %d: no share staged under %s", m.id, fromKeyID)
	}
	return m.st.RenameKey(from, to)
}

func (m *localMember) PublicShare(_ context.Context, keyID string) ([]byte, error) {
	share, err := m.loadShare(keyID)
	if err != nil {
		return nil, err
	}
	return compressPoint(pointFromScalar(share)), nil
}

func (m *localMember) loadShare(keyID string) (*secp.ModNScalar, error) {
	keys, err := m.st.LoadKeys()
	if err != nil {
		return nil, err
	}
	h, ok := keys[m.shareName(keyID)]
	if !ok {
		return nil, fmt.Errorf("member %d: no share for key %s", m.id, keyID)
	}
	b, err := hex.DecodeString(h)
	if err != nil || len(b) != 32 {
		return nil, fmt.Errorf("member %d: stored share for key %s is malformed", m.id, keyID)
	}
	var arr [32]byte
	copy(arr[:], b)
	s := new(secp.ModNScalar)
	if s.SetBytes(&arr) != 0 || s.IsZero() {
		return nil, fmt.Errorf("member %d: stored share for key %s is not a valid scalar", m.id, keyID)
	}
	return s, nil
}

// --- signing -----------------------------------------------------------------

func (m *localMember) NonceCommit(_ context.Context, s SignSession) (*NonceCommitment, error) {
	if _, err := m.loadShare(s.KeyID); err != nil {
		return nil, err // no share for this key: this member cannot take part
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	m.expireLocked()
	if _, exists := m.nonces[s.ID]; exists {
		return nil, fmt.Errorf("member %d: signing session %s already has nonces", m.id, s.ID)
	}
	kh, err := randomScalar(m.rnd)
	if err != nil {
		return nil, err
	}
	kb, err := randomScalar(m.rnd)
	if err != nil {
		return nil, err
	}
	ns := &nonceState{keyID: s.KeyID, hiding: kh, bind: kb, created: time.Now(),
		D: compressPoint(pointFromScalar(kh)), E: compressPoint(pointFromScalar(kb))}
	m.nonces[s.ID] = ns
	// A real member logs what it is being asked to authorize here, and may
	// refuse: the request is advisory, so refusing costs the round nothing but a
	// retry without this member.
	log.Printf("frost: member %d nonce-commits for action=%s aid=%s txid=%s input=%d",
		m.id, s.Request.Action, s.Request.AID, s.Request.TxID, s.Request.InputIndex)
	return &NonceCommitment{From: m.id, D: ns.D, E: ns.E}, nil
}

func (m *localMember) Partial(_ context.Context, s SignSession, pkg *SigningPackage) ([32]byte, error) {
	if pkg == nil {
		return [32]byte{}, fmt.Errorf("member %d: no signing package", m.id)
	}
	m.mu.Lock()
	ns, ok := m.nonces[s.ID]
	if ok {
		delete(m.nonces, s.ID) // consumed either way: never sign twice with one nonce pair
	}
	m.mu.Unlock()
	if !ok {
		return [32]byte{}, fmt.Errorf("member %d: no live nonces for signing session %s (already used, or never committed)", m.id, s.ID)
	}
	if ns.keyID != s.KeyID {
		return [32]byte{}, fmt.Errorf("member %d: session %s committed nonces for key %s, asked to sign for %s",
			m.id, s.ID, ns.keyID, s.KeyID)
	}
	mine, has := pkg.commitmentFor(m.id)
	if !has {
		return [32]byte{}, fmt.Errorf("member %d: the signing package omits my nonce commitment", m.id)
	}
	// The package must carry the exact commitments this member published, or the
	// binding factors were computed over something it never agreed to.
	if !bytesEqual(mine.D, ns.D) || !bytesEqual(mine.E, ns.E) {
		return [32]byte{}, fmt.Errorf("member %d: the signing package carries different nonce commitments than I published", m.id)
	}
	share, err := m.loadShare(s.KeyID)
	if err != nil {
		return [32]byte{}, err
	}
	c, err := newSigningContext(pkg)
	if err != nil {
		return [32]byte{}, err
	}
	return c.partial(m.id, share, ns.hiding, ns.bind)
}

func bytesEqual(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// inSession reports whether an ID belongs to a session's member set. The
// transport's authenticated channel is what proves a share really came from the
// member it names; this check only keeps a stranger's session ID from planting
// state.
func inSession(s DKGSession, id int) bool {
	for _, ident := range s.Members {
		if ident.ID == id {
			return true
		}
	}
	return false
}

// sameSession reports whether a later round's session is the one the member
// committed to. Only the fields the protocol depends on are compared; a member
// must not let a caller change the member set, the threshold or the key a run
// produces between rounds.
func sameSession(pinned, got DKGSession) error {
	if pinned.KeyID != got.KeyID {
		return fmt.Errorf("session %s was committed for key %q, this round says %q", pinned.ID, pinned.KeyID, got.KeyID)
	}
	if pinned.Threshold != got.Threshold {
		return fmt.Errorf("session %s was committed at threshold %d, this round says %d", pinned.ID, pinned.Threshold, got.Threshold)
	}
	if len(pinned.Members) != len(got.Members) {
		return fmt.Errorf("session %s was committed with %d members, this round has %d", pinned.ID, len(pinned.Members), len(got.Members))
	}
	for i := range pinned.Members {
		if pinned.Members[i].ID != got.Members[i].ID {
			return fmt.Errorf("session %s member set changed between rounds", pinned.ID)
		}
	}
	return nil
}

// checkCommitmentSet requires the broadcast commitments to be exactly the
// session's membership, one per member, each attributed to its sender. The
// group key is their sum, so an extra or misattributed entry silently moves it.
func checkCommitmentSet(s DKGSession, comms map[int]*DKGCommitment) error {
	if len(comms) != len(s.Members) {
		return fmt.Errorf("commitment set has %d entries, session %s has %d members", len(comms), s.ID, len(s.Members))
	}
	for _, ident := range s.Members {
		c, has := comms[ident.ID]
		if !has {
			return fmt.Errorf("commitment set is missing member %d of session %s", ident.ID, s.ID)
		}
		if c == nil {
			return fmt.Errorf("commitment set carries no commitment for member %d", ident.ID)
		}
		if c.From != ident.ID {
			return misbehaved(c.From, "its commitment is filed under member %d", ident.ID)
		}
	}
	return nil
}

// sameCommitment reports whether two commitments are byte-identical, so a
// member can confirm the broadcast set carries its own contribution unaltered.
func sameCommitment(a, b *DKGCommitment) bool {
	if a == nil || b == nil || a.From != b.From || len(a.Coeffs) != len(b.Coeffs) {
		return false
	}
	for i := range a.Coeffs {
		if !bytesEqual(a.Coeffs[i], b.Coeffs[i]) {
			return false
		}
	}
	return bytesEqual(a.PoKR, b.PoKR) && a.PoKMu == b.PoKMu
}
